### ISSUE TITLE
Which iOS headers do you use ?

### ISSUE THREAD

**Issue by nabla-c0d3** [ericcastro/Symbolicator#2]
Hi,
Great tool, awesome for reversing Apps :).
I used the precompiled .deb package but I am now trying to compile Symbolicator with rpetrich's fork of theos and rpetrich's private headers (https://github.com/rpetrich/iphoneheaders), and it isn't working:

```
In file included from Tweak.xm:9:
/Users/nabla/Downloads/Symbolicator-master/Symbolicator.h:25:5: error: unknown type name 'VMUProcessDescription'
```

The Symbolication/VMUProcessDescription.h file does not exist in rpetrich's headers, but I've seen it in other iphone headers repos.
Which iOS SDK headers did you use to build Symbolicator ? Or did you class-dump them yourself?
Thanks!

**Comment by ericcastro** [comment]
These are the ones I've been using:
http://eric.cast.ro/debs/Symbolication.zip

Hope that helps!
